docs: updates the shell-introduction page for endless
endlessm/gnome-user-docs pull request #33
Opened 2021-01-22 22:05 UTC by pari-deshmukh

Customizes the visual overview help page as per the user interface and also updates all the introduction page screenshots accordingly.
Also re-implements Endless specific customizations to GNOME User Docs.

2021-01-22 22:05 UTC, eos-shell-build commented
I don't recognize the submitter as a member of @endlessm. Can somebody in @endlessm verify the patch? See https://phabricator.endlessm.com/w/software/build/ci-integration/#pull-requests for more details.

2021-01-25 14:06 UTC, wjt commented
@eos-shell-build ok to test

2021-01-25 14:07 UTC, wjt commented on gnome-help/C/backup-check.page
> - <comment> This doesn't apply to Endless OS
No need to keep this commit and the preceeding commit, which just cancel each other out.

2021-01-25 14:08 UTC, wjt commented on gnome-help/C/backup-how.page
> - <item><p>Any files in the Trash folder. Your Trash folder can be found in
I don't think this hunk helps; in fact it removes useful information which is correct on Endless OS. Let's drop it.

2021-01-27 20:04 UTC, andrunko requested changes
Looking good, some minor comments below.

2021-01-27 21:01 UTC, wjt commented on gnome-help/C/accounts-add.page
> +      to allow Endless access to your online account. Authorize access to
It's been a while since I ran through this process but I am 90% sure that the prompt will be to allow GNOME access to your online account. We don't override the Google API key that GNOME uses.

2021-01-27 21:02 UTC, wjt commented on gnome-help/C/accounts-add.page
> +      to allow Endless access to your online account. Authorize access to
(This should be easy to test.) If it does indeed still show GNOME, no change is needed here.

2021-01-27 21:03 UTC, wjt commented on gnome-help/C/net-firewall-on-off.page
> +      <p>Go to <gui>Overview</gui> in the top left corner of the screen and
Agreed.

2021-02-06 09:34 UTC, pari-deshmukh commented on gnome-help/C/backup-how.page
> - <item><p>Any files in the Trash folder. Your Trash folder can be found in
Reverted in new changeset!

2021-02-06 23:02 UTC, pari-deshmukh commented on gnome-help/C/a11y-font-size.page
> +  # You can use <app>Tweaks</app> to make text size bigger or smaller.
Removed!

2021-02-06 23:04 UTC, pari-deshmukh commented on gnome-help/C/a11y-icon.page
> +    <media its:translate="no" type="image" mime="image/png" src="figures/universal-access-menu.png"/>
Fixed!

2021-02-06 23:08 UTC, pari-deshmukh commented on gnome-help/C/a11y-screen-reader.page
> +  </comment>
Dropped the comment section here!

2021-02-06 23:13 UTC, pari-deshmukh commented on gnome-help/C/accounts-add.page
> +      to allow Endless access to your online account. Authorize access to
I tested it out and it still shows GNOME. So reverting this back to GNOME.

2021-02-06 23:14 UTC, pari-deshmukh commented on gnome-help/C/accounts-remove.page
> +    <p>Many online services provide an authorization token which Endless stores
Fixed!

2021-02-06 23:27 UTC, pari-deshmukh commented on gnome-help/C/shell-exit.page
> +  of the taskbar, expand <gui>Power Off / Log Out</gui>, and select
Fixed!

2021-02-06 23:27 UTC, pari-deshmukh commented on gnome-help/C/shell-introduction.page
> +  click the Endless logo button at the bottom left corner of the screen in the window list.</p>
Removed!

2021-02-06 23:30 UTC, pari-deshmukh commented on gnome-help/C/shell-introduction.page
> +  <p if:test="platform:endless">On the bottom left corner of the screen, you will find a list of
Makes sense! Fixed this.

2021-02-06 23:30 UTC, pari-deshmukh commented on gnome-help/C/shell-introduction.page
> +  the Endless desktop and the running applications.</p>
Fixed!

2021-02-06 23:31 UTC, pari-deshmukh commented on gnome-help/C/shell-introduction.page
> +    <p>The window list at the bottom of the screen provides access to all your
Fixed!

2021-02-08 18:01 UTC, andrunko requested changes
Looks mostly good but looks like some review comments got missed during this round of updates. I also left a few extra comments that I missed during initial review.

2021-02-08 20:50 UTC, pari-deshmukh commented on gnome-help/C/a11y-icon.page
> +  <gui>Overview</gui> button — this tells you which item on the taskbar is
Fixed!

2021-02-08 20:50 UTC, pari-deshmukh commented on gnome-help/C/backup-thinkabout.page
> +  and need to be translated. You can find the correct translations for your
Makes sense!

2021-02-08 20:53 UTC, pari-deshmukh commented on gnome-help/C/shell-introduction.page
> +      <p>Endless Desktop</p>
Fixed!

2021-02-08 20:53 UTC, pari-deshmukh commented on gnome-help/C/shell-introduction.page
> +  the Endless Desktop and the running applications.</p>
Updated!

2021-02-08 20:54 UTC, pari-deshmukh commented on gnome-help/C/shell-introduction.page
> +      <p>Endless features a completely reimagined user interface designed to
Done!

2021-02-08 20:54 UTC, pari-deshmukh commented on gnome-help/C/shell-introduction.page
> +  <title>Visual overview of Endless</title>
Already fixed!

2021-02-09 13:09 UTC, pari-deshmukh commented
@wjt @andrunko I have implemented all the changes requested and have implemented additional changes to the user docs. Also, I have rebased the branch with the latest GNOME user docs master now. Please review.

2021-02-09 16:03 UTC, andrunko requested changes
Just some small notes, looking good.

2021-02-09 16:03 UTC, andrunko commented on gnome-help/C/display-brightness.page
> +  of the taskbar and adjust the screen brightness slider to the value you want
Also "system menu" for screen brightness.

2021-02-09 16:03 UTC, andrunko commented on gnome-help/C/display-night-light.page
> +        the user menu.</p>
"system menu" also for night light.

2021-02-09 16:03 UTC, andrunko commented on gnome-help/C/net-manual.page
> +      <gui xref="shell-introduction#usermenu">user menu</gui> from the right side of
"system menu"

2021-02-09 16:13 UTC, wjt commented on gnome-help/C/.yelp-tools.cfg
> +version = gnome:40
Will this have any visible effect in the rendered help? If so, it'll be wrong because we will be shipping GNOME 3.38. If not, then it's harmless to have this here.

We could rebase onto the commit before this one, side-stepping the problem.

2021-02-12 22:33 UTC, sayak-sarkar commented on gnome-help/C/touchscreen-gestures.page
> +    <td><p><em>Bring down the user menu</em></p>
I'm not sure how to verify this, and as such skipping this changeset for now.
@wjt Do you have any idea about Endless OS's Touch-screen gestures?

2021-02-12 22:36 UTC, pari-deshmukh commented on gnome-help/C/touchscreen-gestures.page
> +    <td><p><em>Bring down the user menu</em></p>
Not sure how this would look like on a touchscreen device. Maybe @wjt has some idea?

2021-02-12 22:43 UTC, pari-deshmukh commented on gnome-help/C/.yelp-tools.cfg
> +version = gnome:40
This seems to be configuration very specific to yelp tools and as such doesn't show any visible effects in the rendered help docs.

2021-02-17 21:48 UTC, merged

2021-02-17 21:48 UTC, andrunko commented
Thanks @pari-deshmukh, landed these changes + a few fixup commits on top.