first pass for eos5
endlessm/gnome-user-docs pull request #42
Opened 2022-12-13 17:22 UTC by MichaelDrydenEndless

Work in Progress

https://phabricator.endlessm.com/T33856

2022-12-13 17:42 UTC, cassidyjames commented on gnome-help/C/a11y-contrast.page
> +      <p>Go to the Dekstop and start typing <gui>Accessibility</gui>.</p>
Itty bitty typo

```suggestion
      <p>Go to the Desktop and start typing <gui>Accessibility</gui>.</p>
```

2022-12-13 17:42 UTC, cassidyjames commented on gnome-help/C/a11y-icon.page
> +      <p>Go to the Dekstop and start typing <gui>Accessibility</gui>.</p>
```suggestion
      <p>Go to the Desktop and start typing <gui>Accessibility</gui>.</p>
```

2022-12-13 17:42 UTC, cassidyjames commented on gnome-help/C/a11y-right-click.page
> +      <p>Go to the Dekstop and start typing <gui>Accessibility</gui>.</p>
```suggestion
      <p>Go to the Desktop and start typing <gui>Accessibility</gui>.</p>
```

2022-12-14 11:25 UTC, wjt commented on gnome-help/C/a11y-braille.page
> +  <p>The <app>Orca</app> screen reader can speak the user interface.</p>
I think it's OK to just leave this paragraph as-is. This section is about Braille displays, not audible screen-reading. And the "Depending on…" sentence is technically true, in the sense that Orca is always installed.

2022-12-14 11:25 UTC, wjt commented on gnome-help/C/a11y-contrast.page
> +      <p>Go to the Dekstop and start typing <gui>Accessibility</gui>.</p>
I don't like the Germanic Noun Capitalization of Desktop. I suggest:

<gui>desktop</gui>

2022-12-14 11:27 UTC, wjt commented on gnome-help/C/accounts-add.page
> +      to allow Endless access to your online account. Authorize access to
Actually the prompt does ask you to allow GNOME access, so the original text is correct.

2022-12-21 23:46 UTC, cassidyjames commented on gnome-help/C/a11y-visualalert.page
> +      <p>Go tp the desktop and start typing <gui>Accessibility</gui>.</p>
```suggestion
      <p>Go to the desktop and start typing <gui>Accessibility</gui>.</p>
```

2022-12-21 23:47 UTC, cassidyjames commented on gnome-help/C/a11y-locate-pointer.page.stub
> +      <p>Click the Battery Icon on the top bar and select <gui>Settings</gui>.</p>
```suggestion
      <p>Click the battery icon on the top bar and select <gui>Settings</gui>.</p>
```

2022-12-21 23:48 UTC, cassidyjames commented on gnome-help/C/accounts-remove.page
> +    for your Desktop.</p>
```suggestion
    for your desktop.</p>
```

2022-12-21 23:48 UTC, cassidyjames commented on gnome-help/C/accounts-remove.page
> +    <p>Many online services provide an authorization token which your Desktop stores
```suggestion
    <p>Many online services provide an authorization token which your desktop stores
```

2023-01-05 15:40 UTC, wjt commented on gnome-help/C/shell-windows.page
> +  applications. Using both the gui>desktop</gui> and the <em>dash</em>, you can launch new applications and control
```
Error: Could not parse document:
 ..//C/shell-windows.page:30:  parser  error :  Opening and ending tag mismatch: p line 29 and gui
   applications. Using both the gui>desktop</gui> and the <em>dash</em>, you can 
```

```suggestion
  applications. Using both the <gui>desktop</gui> and the <em>dash</em>, you can launch new applications and control
```

2023-01-05 15:41 UTC, wjt commented on gnome-help/C/sound-nosound.page
> +      <p>Go to the gui>desktop</gui> and start typing <gui>Sound</gui>.</p>
Same error here

2023-01-05 15:42 UTC, wjt commented on gnome-help/C/tips-specialchars.page
> -  <section id="compose">
Why are we removing this section?

2023-01-05 15:44 UTC, wjt commented on gnome-help/C/user-changepicture.page
> -  webcam.</p>
Why are we removing this sentence? It's true: you can take a login photo with your webcam.

2023-01-05 15:46 UTC, wjt commented on gnome-help/C/a11y-visualalert.page
> +      <p>Go tp the <gui>desktop</gui> and start typing <gui>Accessibility</gui>.</p>
```suggestion
      <p>Go to the <gui>desktop</gui> and start typing <gui>Accessibility</gui>.</p>
```

2023-01-05 15:54 UTC, wjt commented on gnome-help/C/sharing-desktop.page
> +  <p>You can let other people view and control your <gui>desktop</gui> from another
I don't think we should make this change and the similar changes in this file, for a sad technical reason: adding this `<gui>...</gui>` tag will invalidate all translations of this entire paragraph and make us/our community either retranslate it, or show the paragraph in English.

2023-01-05 15:55 UTC, wjt commented on gnome-help/C/shell-apps-open.page
> +  also open the <gui>desktop</gui> by pressing the <key xref="keyboard-key-super">Super</key>
This isn't quite true. Pressing Super triggers the activities overview. Double-pressing Super, or pressing Super+A, goes to the desktop.

2023-01-05 15:56 UTC, wjt commented on gnome-help/C/shell-exit.page
> +  <p>To lock your screen, click the User menu on the right side of the top
We should drop this change: we used to replace GNOME's system menu with a user menu, but we have restored GNOME's system menu.

2023-01-05 16:00 UTC, wjt commented on gnome-help/C/shell-introduction.page
> +        streamlined user experience using a customized <gui>desktop</gui> environment forked from GNOME 4.</p>
I think the point of this paragraph was to explain what the term "GNOME" means, but I've always been a bit unhappy with it. This is pretty much the first page of the documentation and we're using the term "Linux" and "forked". I think we should reword it to something like (improvements and suggestions welcome!):

```suggestion
        <p>The Endless OS desktop is a customized version of a desktop called “GNOME”. You will see the terms “Endless OS” and “GNOME” used interchangeably in this documentation.</p>
```

2023-01-05 16:02 UTC, wjt commented on gnome-help/C/shell-introduction.page
> +<section id="usermenu">
As above, we no longer have a user menu. We should stick with the upstream term "system menu" here and below.

2023-01-05 16:03 UTC, wjt commented on gnome-help/C/shell-introduction.page
> +      <p>Window List</p>
I think we could refer to this as either the dash (following the existing  GNOME terminology and used elsewhere in this documentation) or the dock, rather than window list.

2023-01-05 16:04 UTC, wjt commented on gnome-help/C/shell-keyboard-shortcuts.page
> +use your <gui>desktop</gui> and applications more efficiently. If you cannot use a
As above, let's not invalidate all translations of this paragraph:

```suggestion
use your desktop and applications more efficiently. If you cannot use a
```

2023-01-05 16:04 UTC, wjt commented on gnome-help/C/shell-keyboard-shortcuts.page
> +    <td><p>Switch between the <gui>Activities</gui> overview and <gui>desktop</gui>. In
```suggestion
    <td><p>Switch between the <gui>Activities</gui> overview and desktop. In
```

2023-01-05 16:04 UTC, wjt commented on gnome-help/C/shell-windows.page
> +  <p>Like other <gui>desktop</gui>, the system uses windows to display your running
```suggestion
  <p>Like other desktops, the system uses windows to display your running
```

2023-01-05 16:06 UTC, wjt commented on gnome-help/C/user-add.page
> +      right of accounts on the left, to add a new user account.</p>
Great catch! I suggest a simplification:

```suggestion
      <p>Press the <gui style="button">Add User...</gui> button, at the top of the window, to add a new user account.</p>
```

2023-01-05 16:08 UTC, wjt commented on gnome-help/C/user-delete.page
> +      <gui style="button">Remove User...</gui> button, above the list of accounts on the
The button is not above the list of accounts. I suggest splitting this step in two:

- Select the user that you want to delete.
- Scroll to the bottom of the window and press the <gui style="button">Remove User...</gui> button to delete that user account.

2023-01-05 16:12 UTC, wjt reviewed
This is very thorough work! Looking pretty close.

2023-01-06 03:02 UTC, cassidyjames requested changes
Just a few things I noticed. It might not be worth the time, but I also wonder if any time we show `<gui>desktop</gui>` we should still link to the section explaining it, e.g. `<gui xref="shell-introduction#activities">desktop</gui>`.

2023-01-06 20:05 UTC, cassidyjames approved these changes
I think this is good to merge from my perspective; we can continue to review in context and iterate if needed.

@MichaelDrydenEndless I think you'll need to mark the PR as ready to merge instead of a draft.

2023-01-06 20:06 UTC, merged